### PR TITLE
stream_aligner: normalize search behaviours in indexes, and the meaning of bounds in intervals

### PR DESCRIPTION
**Pull request by doudou**
This commit moves the stream aligner in a [min, max[ interpretation of intervals,
which is really really so much easier to handle. In particular, it
behaves much better when searching for a sample around a value, since
there is an easy past-the-end value (size) while there is none for
a last-sample-before behaviour (-1 ???)

It also tries to clear up some related unit tests, and add much needed documentation

### CODE REVIEW

**Comment by D-Alex** [comment]
after adding two missing variable the first stream gets exported but the second one fails because of the following error:

    /home/aduda/dev/rock_master/tools/pocolog/lib/pocolog/stream_index.rb:87:in `sample_number_by_internal_time': undefined method `bsearch' for #<Array:0x00000002a69f80> (NoMethodError)
	from /home/aduda/dev/rock_master/tools/pocolog/lib/pocolog/stream_aligner.rb:416:in `find_first_stream_sample_after'
	from /home/aduda/dev/rock_master/tools/pocolog/lib/pocolog/stream_aligner.rb:393:in `find_first_stream_sample_at_or_after'
	from /home/aduda/dev/rock_master/tools/pocolog/lib/pocolog/stream_aligner.rb:359:in `block in export_to_file'
	from /home/aduda/dev/rock_master/tools/pocolog/lib/pocolog/stream_aligner.rb:346:in `each'
	from /home/aduda/dev/rock_master/tools/pocolog/lib/pocolog/stream_aligner.rb:346:in `export_to_file'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/log/replay.rb:1048:in `export_to_file'

**Comment by doudou** [comment]
Are you running on 1.9 ? bsearch is present since 2.0

**Comment by D-Alex** [comment]
Seems to work with ruby2.0. I was indeed using ruby 1.9.
